### ISSUE TITLE
../data/arrays/Nor848A-10.mat

### ISSUE THREAD

**Issue by sunjunlishi** [jorgengrythe/beamforming#1]
whre is the data?could you supply it

**Comment by jorgengrythe** [comment]
The .mat file only contained xPos, yPos and zPos values for the microphone positions. And also a weighting vector (hiResWeights). Those values are sort of business confidential, so I'm afraid I cant release them. Basically you can change that line with your own xPos =, yPos =, zPos =, w = and you're good to go. Or make your own .mat file with xPos, yPos, zPos and w.
