### ISSUE TITLE
can't find ring-48.mat 

### ISSUE THREAD

**Issue by seaiceli** [jorgengrythe/beamforming#3]
>> BeampatternMinimumVariance
错误使用 load
无法读取文件 '../data/arrays/ring-48.mat'。没有此类文件或目录。

出错 BeampatternMinimumVariance (line 19)
load ../data/arrays/ring-48.mat

**Comment by jorgengrythe** [comment]
I have removed the .mat-files, but here's the matlab code to create the x, y, z positions for the ring-48 array.

```
% Create circular array
nElements = 48;
radius = 0.75;

[xPos, yPos] = pol2cart((0:1/nElements:1-1/nElements)*2*pi, ones(1,nElements)*radius);
zPos = zeros(1, numel(xPos));
elementWeights = ones(1,numel(xPos))/numel(xPos);
```
